AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: My SAM Application

Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/my_lambda_function.handler
      Runtime: nodejs14.x
      Events:
        MyApi:
          Type: Api
          Properties:
            Path: /myapi
            Method: GET

Outputs:
  MyApi:
    Description: "API Gateway endpoint URL for the MyLambdaFunction"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/myapi/"
